version: '3.8'

services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - .:/app  # permite que dbtrack.db e código fiquem persistentes fora do container
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
