version: '3.8'

services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - flask-network

  db:
    image: postgres:13
    container_name: flask-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_name
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge

volumes:
  postgres-data:
